version: '3.7'
services:
  react:
    container_name: front-documents-manager-docker-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3009:3000'