export const initialSections = [
    { idSection: "1",
      title: "Solicitud de actualización de incidencias en la Gestión Horaria",
      description: "Todas las solicitudes de actualización de incidencias en la Gestión Horaria deben estar firmadas por el interesado y validadas por el Responsable de Unidad/ Sección o Subdirector correspondiente",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 1},
      { idSection: "2",
      title: "Modificación datos",
      description: "Este trámite debe realizarse a través de Politécnica Virtual",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 3},
      { idSection: "3",
      title: "Solicitud genérica",
      description: "Esta solicitud es genérica y sirve para distintas ocasiones. Es importante poner en el pie del documento a quién va dirigida la solicitud. En el formato PDF vienen definidas las opciones más comunes.",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 2},
      { idSection: "4",
      title: "Solicitud de Compatibilidad",
      description: "Es necesario presentar siempre cuatro documentos: 1. Solicitud de compatibilidad con una segunda actividad, ya sea en el sector privado o en el público (son impresos diferentes). 2. Certificado de horario en la Escuela. 3. Certificado del horario a realizar en la segunda empresa. 4. Una vida laboral actualizada. Impresos",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 4},
      { idSection: "5",
      title: "Solicitud contratación temporal",
      description: "",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 5},
      { idSection: "6",
      title: "Otros impresos UPM para PAS Laboral",
      description: "",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 6},
      { idSection: "7",
      title: "Otros impresos UPM para PAS Funcionario",
      description: "",
      createdAt: new Date(),
      updatedAt: new Date(),
      index: 7}
  ];